### ISSUE TITLE
Removing Tag

### ISSUE THREAD

**Issue by Janak-Nirmal** [freak4pc/SMTagField#3]
I downloaded and tried deleting tags but was not able to delete tag. Can you please throw light on this ? 

I checked code and found method deleteBackward but was not being called anywhere. Probably missing code to call ? 

Thax

**Comment by freak4pc** [comment]
Hey Janak,
Can you try using the Example project and see if you're experiencing the
same issue ?
It works fine for me.

Or are you trying to manually remove tags? (programatically)

Shai

**Comment by Janak-Nirmal** [comment]
Hey Shai, 

Thank you for your quick reply. I checked sample project, but not succeeded. What I am looking for is like remove added tags on backspace.  

Thax

**Comment by skull-squadron** [comment]
Backspace works fine in iOS >= 6.0 but not iOS < 6.0.

**Comment by freak4pc** [comment]
Hey Barry, thanks for that.
I don't have an iOS 5 device at hand but I'll try on the simulator and let
u know.

**Comment by skull-squadron** [comment]
@freak4pc Cool.  Didja mean to implement the `UIKeyInput` protocol in `SMTagField.m`? `deleteBackward` isn't getting called (inserted an NSLog).

**Comment by freak4pc** [comment]
Not near the computer right now, but If you wanna try and fix it feel free
to fork and patch!

**Comment by skull-squadron** [comment]
"Patches welcome!" ;) We'll see.

**Comment by skull-squadron** [comment]
I gotta run myself, here's the fix: http://bjhomer.blogspot.com/2011/11/detecting-backspace-in-uitextfield.html

**Comment by skull-squadron** [comment]
Now I gotta take a hike, literally.  Stanford Dish. :)

**Comment by freak4pc** [comment]
Hey @steakknife , Thank you very much for helping - 
I think I'm gonna fix this up another way since your code seems a bit of an overkill for the condition, plus it doesn't fit with the rest of the Coding Conventions. Also, I have no desire to support ARC since its support in iOS >= 5.0 and is stable enough... Maintaining a non-ARC branch would require way too much overhead.

Again, I really appreciate wanting to help. 

I hope i'll get a patch up for this sooner then later. Cheers!

**Comment by freak4pc** [comment]
Hey @Janak-Nirmal and @steakknife , 
After careful consideration I've decided to only offer support from iOS >= 6.0 .

The UIKeyInput method "deleteBackward" isn't being called under iOS6 (even though the docs claim it works after iOS 3.2).

The only way to make this work on iOS5 would be very hacky or require adding way too much unneeded code, and since iOS >= 6.0 insallations are 96% of iOS population, I don't see the need to "fix it". 

Hope you understand and cheers!
Shai.
